-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_appearancemodifier_profile`;
DROP TABLE IF EXISTS `civicrm_appearancemodifier_petition`;
DROP TABLE IF EXISTS `civicrm_appearancemodifier_event`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_appearancemodifier_event
-- *
-- * This table contains settings for modified events
-- *
-- *******************************************************/
CREATE TABLE `civicrm_appearancemodifier_event` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Appearance-modifier Event Setting ID',
  `event_id` int unsigned NULL DEFAULT NULL COMMENT 'FK to civicrm_event',
  `layout_handler` varchar(511) NULL DEFAULT NULL COMMENT 'Layout handler class',
  `background_color` varchar(15) NULL DEFAULT NULL COMMENT 'Color code of background in #ffffff format',
  `invert_consent_fields` tinyint NULL DEFAULT NULL COMMENT 'Are consent checkboxes inverted?',
  `custom_social_box` tinyint NULL DEFAULT NULL COMMENT 'Is custom social box used?',
  `external_share_url` text NULL DEFAULT NULL COMMENT 'This link will be shared in a custom social box',
  `add_placeholder` tinyint NULL DEFAULT NULL COMMENT 'Should we add placeholders?',
  `hide_form_labels` tinyint NULL DEFAULT NULL COMMENT 'Should we hide form labels?',
  `font_color` varchar(15) NULL DEFAULT NULL COMMENT 'Color code of fonts in #ffffff format',
  `consent_field_behaviour` text NULL DEFAULT NULL COMMENT 'Select consent logic operation mode',
  `custom_settings` text NULL DEFAULT NULL COMMENT 'Custom serialized data for PHP',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_appearancemodifier_event_event_id FOREIGN KEY (`event_id`) REFERENCES `civicrm_event`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_appearancemodifier_petition
-- *
-- * This table contains settings for modified petitions
-- *
-- *******************************************************/
CREATE TABLE `civicrm_appearancemodifier_petition` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Appearance-modifier Petition Setting ID',
  `survey_id` int unsigned NULL DEFAULT NULL COMMENT 'FK to civicrm_survey',
  `layout_handler` varchar(511) NULL DEFAULT NULL COMMENT 'Layout handler class',
  `background_color` varchar(15) NULL DEFAULT NULL COMMENT 'Color code of background in #ffffff format',
  `additional_note` text NULL DEFAULT NULL COMMENT 'This text will be displayed after submit button',
  `petition_message` text NULL DEFAULT NULL COMMENT 'Petition message template',
  `invert_consent_fields` tinyint NULL DEFAULT NULL COMMENT 'Are consent checkboxes inverted?',
  `target_number_of_signers` int unsigned NULL DEFAULT NULL COMMENT 'Target number of the petition signers',
  `custom_social_box` tinyint NULL DEFAULT NULL COMMENT 'Is custom social box used?',
  `external_share_url` text NULL DEFAULT NULL COMMENT 'This link will be shared in a custom social box',
  `add_placeholder` tinyint NULL DEFAULT NULL COMMENT 'Should we add placeholders?',
  `hide_form_labels` tinyint NULL DEFAULT NULL COMMENT 'Should we hide form labels?',
  `font_color` varchar(15) NULL DEFAULT NULL COMMENT 'Color code of fonts in #ffffff format',
  `signers_block_position` text NULL DEFAULT NULL COMMENT 'Position where the number of petition signers is displayed',
  `consent_field_behaviour` text NULL DEFAULT NULL COMMENT 'Select consent logic operation mode',
  `custom_settings` text NULL DEFAULT NULL COMMENT 'Custom serialized data for PHP',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_appearancemodifier_petition_survey_id FOREIGN KEY (`survey_id`) REFERENCES `civicrm_survey`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_appearancemodifier_profile
-- *
-- * This table contains settings for modified profiles
-- *
-- *******************************************************/
CREATE TABLE `civicrm_appearancemodifier_profile` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Appearance-modifier Profile Setting ID',
  `uf_group_id` int unsigned NOT NULL COMMENT 'FK to civicrm_uf_group',
  `layout_handler` varchar(511) NULL DEFAULT NULL COMMENT 'Layout handler class',
  `background_color` varchar(15) NULL DEFAULT NULL COMMENT 'Color code of background in #ffffff format',
  `additional_note` text NULL DEFAULT NULL COMMENT 'This text will be displayed after submit button',
  `invert_consent_fields` tinyint NULL DEFAULT NULL COMMENT 'Are consent checkboxes inverted?',
  `add_placeholder` tinyint NULL DEFAULT NULL COMMENT 'Should we add placeholders?',
  `hide_form_labels` tinyint NULL DEFAULT NULL COMMENT 'Should we hide form labels?',
  `font_color` varchar(15) NULL DEFAULT NULL COMMENT 'Color code of fonts in #ffffff format',
  `consent_field_behaviour` text NULL DEFAULT NULL COMMENT 'Select consent logic operation mode',
  `custom_settings` text NULL DEFAULT NULL COMMENT 'Custom serialized data for PHP',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_appearancemodifier_profile_uf_group_id FOREIGN KEY (`uf_group_id`) REFERENCES `civicrm_uf_group`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
